version: '3'
services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
      args:
        - WORK_DIR=${WORK_DIR}
    container_name: node
    tty: true
    ports:
      - ${PORT}:3000
    networks:
      - shared-network
    volumes:
      - ./:${WORK_DIR}

networks:
  shared-network:
    external: true
