name: test

on: [push]

jobs:
  test:
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-latest]
        node-version: [14.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run CI tests
        run: make ci
